# image will be published to ghcr.io/<user>/<name>
name: sediment
# description will be included in the image's metadata
description: Sericea-based image with quality of life improvements

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main

# latest is also supported if you want new updates ASAP
image-version: 39 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    install:
      - fish

  # configure what to pull in from ublue-os/bling
  - type: bling 
    install:
      - justfiles 
      - ublue-os-wallpapers
      - ublue-update
      - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      - laptop # installs TLP and configures your system for laptop usage

  - type: script
    scripts:
      # set up the proper policy & signing files for signed images to work
      - signing.sh
